
services:

  corevox_app_dev:
    container_name: ${PUBLIC_APP_NAME}
    restart: always
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    depends_on:
      - corevox_postgres_dev
      - corevox_coturn_dev
    volumes:
      - ./app:/app
      - /app/_build
      - /app/deps
    ports:
      - "4000:4000"
    env_file: ./.env
    environment:
      - MIX_ENV=dev
      - GUARDIAN_SECRET=${GUARDIAN_SECRET}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_URL=${POSTGRES_URL}
      - PUBLIC_CLIENT_HTTP_URL=${PUBLIC_CLIENT_HTTP_URL}
    command: sh -c "mix setup && mix phx.server"

  corevox_web_dev:
    container_name: corevox_web_dev
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    ports:
      - "4321:4321"

    depends_on:
      - corevox_postgres_dev
      - corevox_coturn_dev
      - corevox_app_dev
    volumes:
      - ./web:/app
      - /app/node_modules
    env_file: ./.env

    environment:
      - NODE_ENV=development
      - PUBLIC_SIGNAL_HOST=${PUBLIC_SIGNAL_HOST}
      - PUBLIC_SIGNAL_PORT=${PUBLIC_SIGNAL_PORT}
      - PUBLIC_SIGNAL_PATH=${PUBLIC_SIGNAL_PATH}
      - PUBLIC_APP_NAME=${PUBLIC_APP_NAME}
      - PUBLIC_APP_HTTP_URL=${PUBLIC_APP_HTTP_URL}
      - PUBLIC_APP_SOCKET_URL=${PUBLIC_APP_SOCKET_URL}
      - PUBLIC_TURN_USER=${PUBLIC_TURN_USER}
      - PUBLIC_TURN_PASSWORD=${PUBLIC_TURN_PASSWORD}
      - PUBLIC_TURN_REALM=${PUBLIC_TURN_REALM}
      - PUBLIC_STUN_SERVER_URL=${PUBLIC_STUN_SERVER_URL}
      - PUBLIC_TURN_SERVER_URL=${PUBLIC_TURN_SERVER_URL}

    command: npm run dev -- --host 0.0.0.0

  corevox_signal_server_dev:
    container_name: corevox_signal_server_dev
    restart: unless-stopped
    env_file: ./.env
    build:
      context: ./signal-server
      dockerfile: Dockerfile.dev
    ports:
      - "9000:9000"
    volumes:
      - ./signal-server:/usr/src/app
      - ./signal-server/node_modules:/usr/src/app/node_modules



  corevox_coturn_dev:
    container_name: corevox_coturn_dev
    image: coturn/coturn
    restart: unless-stopped
    ports:
      - "3478:3478/udp"
      - "3478:3478/tcp"
      - "49160-49200:49160-49200/udp"
    env_file: ./.env
    command: >
      turnserver
        -a
        -v
        --no-tls
        --no-dtls
        --lt-cred-mech
        --fingerprint
        --user=${PUBLIC_TURN_USER}:${PUBLIC_TURN_PASSWORD}
        --realm=${PUBLIC_TURN_REALM}
        --listening-ip=0.0.0.0
        --min-port=49160
        --max-port=49200
        --log-file=/var/log/turn_2025-09-06.log
        --no-multicast
        --cli-password=${COTURN_CLI_PASSWORD}
    volumes:
      - ./coturn/logs:/var/log

  corevox_postgres_dev:
    container_name: ${POSTGRES_HOST}
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    env_file: ./.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}

    volumes:
      - ./data:/var/lib/postgresql/data
