
services:

  corevox_app_dev:
    container_name: ${PUBLIC_APP_NAME}
    restart: always
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    depends_on:
      - corevox_postgres_dev
      - corevox_coturn_dev
    volumes:
      - ./app:/app
      - /app/_build
      - /app/deps
    ports:
      - "4000:4000"
    env_file: ./.env
    environment:
      - MIX_ENV=dev
      - GUARDIAN_SECRET=${GUARDIAN_SECRET}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_URL=${POSTGRES_URL}
      - PUBLIC_CLIENT_HTTP_URL=${PUBLIC_CLIENT_HTTP_URL}
    command: sh -c "mix setup && mix phx.server"

  corevox_web_dev:
    container_name: corevox_web_dev
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    ports:
      - "4321:4321"

    depends_on:
      - corevox_postgres_dev
      - corevox_coturn_dev
      - corevox_app_dev
    volumes:
      - ./web:/app
      - /app/node_modules
    env_file: ./.env

    environment:
      - NODE_ENV=development
      - PUBLIC_APP_NAME=${PUBLIC_APP_NAME}
      - PUBLIC_APP_HTTP_URL=${PUBLIC_APP_HTTP_URL}
      - PUBLIC_APP_SOCKET_URL=${PUBLIC_APP_SOCKET_URL}
      - PUBLIC_TURN_USER=${PUBLIC_TURN_USER}
      - PUBLIC_TURN_PASSWORD=${PUBLIC_TURN_PASSWORD}
      - PUBLIC_TURN_REALM=${PUBLIC_TURN_REALM}

    command: npm run dev -- --host 0.0.0.0

  corevox_coturn_dev:
    container_name: corevox_coturn_dev
    image: instrumentisto/coturn
    restart: unless-stopped
    ports:
      - "3478:3478"
      - "3478:3478/tcp"
      - "49160-49200:49160-49200/udp"
    command: >
      turnserver
        -a
        -v
        --no-dtls
        --no-tls
        --lt-cred
        --fingerprint
        --user=${PUBLIC_TURN_USER}:${PUBLIC_TURN_PASSWORD}
        --realm=${PUBLIC_TURN_REALM}
        --total-quota=100
        --bps-capacity=0
        --min-port=49160
        --max-port=49200
    env_file:
      - ./.env

  corevox_postgres_dev:
    container_name: ${POSTGRES_HOST}
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    env_file: ./.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}

    volumes:
      - ./data:/var/lib/postgresql/data
