FROM elixir:1.18-alpine


RUN apk add --no-cache \
    inotify-tools \
    build-base \
    git \
    nodejs \
    npm \
    postgresql-client

WORKDIR /app


RUN mix local.hex --force && \
    mix local.rebar --force


COPY mix.exs mix.lock ./

RUN mix deps.get

COPY . .


EXPOSE 4000

CMD ["mix", "phx.server"]
